spring.application.name=BloodDonor

spring.datasource.url=jdbc:mysql://localhost:3306/BloodDonor
spring.datasource.username=root
spring.datasource.password=Shreyansh@1975

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
